# Generated by Django 3.2.5 on 2021-11-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customermsg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='client_email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='client_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='client_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
