# Generated by Django 3.2.7 on 2021-10-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211020_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Na čekanju'), ('accepted', 'Prihvaćeno'), ('Rejected', 'Odbijeno')], default='Pending', max_length=200),
        ),
    ]
