# Generated by Django 3.2.7 on 2021-10-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Na čekanju'), ('accepted', 'Prihvaćeno'), ('Rejected', 'Odbijeno')], default='Pending', max_length=200),
        ),
    ]
