# Generated by Django 3.2.5 on 2021-10-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20211027_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('na_cekanju', 'Na čekanju'), ('prihvaceno', 'Prihvaćeno'), ('odbijeno', 'Odbijeno')], default='Na čekanju', max_length=200),
        ),
    ]
