# Generated by Django 3.2.5 on 2021-10-28 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderitem_panelstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_number',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
