# Generated by Django 3.2.5 on 2021-10-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderitem_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_number',
        ),
    ]
