# Generated by Django 3.2.5 on 2021-11-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_remove_order_msgvar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='msgVar',
            field=models.IntegerField(default=1),
        ),
    ]
