# Generated by Django 3.2.5 on 2021-11-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_order_msgvar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='msgVar',
        ),
    ]
